### ISSUE TITLE
Under what license is the GhidraLibraryDemo?

### ISSUE THREAD

**Issue by theuserbl** [nshalabi/Coding-Ghidra#1]
Ghidra https://github.com/NationalSecurityAgency/ghidra is licensed under the Apache 2.0 license. Under what license is your GhidraLibraryDemo ?

**Comment by nshalabi** [comment]
Thank you, the samples are just coding demos, no permissions are needed for usage, redistribution or modification. I added a comment at the java file header.
Much appreciated.
