### ISSUE TITLE
which ghira version

### ISSUE THREAD

**Issue by FizzFish** [nshalabi/Coding-Ghidra#2]
Hello, this is a good project. 
However, when I build the project, some errors occur related to the ghidra.jar.
So which ghidra version should I used?

**Comment by nshalabi** [comment]
Thank you, I tried it with the latest version of Ghidra and it did not work, I found many breaking changes, I fixed it and will soon upload a new version + new instructions on how to build the JAR file.

**Comment by nshalabi** [comment]
Fixed, thanks again for the feedback.
